version: '3'
services:
    php:
        container_name: mock_php
        build:
            context: ./
            dockerfile: ./docker-files/Dockerfile
        volumes:
            - $PWD:/app/
        privileged: true
        ports:
            - "8888:80"
