#!/usr/bin/with-contenv sh

case ${environment} in
  "dev" )
    cp /app/.env.dev /app/.env
    ;;
  "uat" )
    cp /app/.env.uat /app/.env
    ;;
  "prod" )
    cp /app/.env.prod /app/.env
    ;;
  * )
    ;;
esac

echo "DB_HOST=$DB_HOST" >> /app/.env
echo "DB_DATABASE=$DB_DATABASE" >> /app/.env
echo "DB_USERNAME=$DB_USERNAME" >> /app/.env
echo "DB_PASSWORD=$DB_PASSWORD" >> /app/.env
echo "MAIL_USERNAME=$ADMIN_MAIL" >> /app/.env
echo "MAIL_FROM_ADDRESS=$ADMIN_MAIL" >> /app/.env
echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> /app/.env

# optimize base on environment
#cd /app
#php artisan config:cache && \
#php artisan route:trans:cache && \
#php artisan view:cache
php artisan  optimize:clear
