#!/usr/bin/with-contenv sh

case ${environment} in
  "dev" )
    cp /app/.env.dev /app/.env
    ;;
  "uat" )
    cp /app/.env.uat /app/.env
    ;;
  "prod" )
    cp /app/.env.prod /app/.env
    ;;
  * )
    ;;
esac

# optimize base on environment
#cd /app
#php artisan config:cache && \
#php artisan route:trans:cache && \
#php artisan view:cache
php artisan  optimize:clear
